
--------------------------------------------------------
--  File created - Saturday-May-20-2017  
-- USER SQL
CREATE USER shareit IDENTIFIED BY "shareit"  ;

-- QUOTAS

-- ROLES
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO shareit WITH ADMIN OPTION;
GRANT "DBA" TO shareit WITH ADMIN OPTION;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO shareit WITH ADMIN OPTION;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO shareit WITH ADMIN OPTION;
GRANT "CTXAPP" TO shareit WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO shareit WITH ADMIN OPTION;
GRANT "CONNECT" TO shareit WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO shareit WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO shareit WITH ADMIN OPTION;
GRANT "APEX_ADMINISTRATOR_ROLE" TO shareit WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO shareit WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO shareit WITH ADMIN OPTION;
GRANT "XDB_SET_INVOKER" TO shareit WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO shareit WITH ADMIN OPTION;
GRANT "DBFS_ROLE" TO shareit WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO shareit WITH ADMIN OPTION;
GRANT "HS_ADMIN_SELECT_ROLE" TO shareit WITH ADMIN OPTION;
GRANT "PLUSTRACE" TO shareit WITH ADMIN OPTION;
GRANT "RESOURCE" TO shareit WITH ADMIN OPTION;
GRANT "AQ_ADMINISTRATOR_ROLE" TO shareit WITH ADMIN OPTION;
GRANT "DELETE_CATALOG_ROLE" TO shareit WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO shareit WITH ADMIN OPTION;
GRANT "REGISTRYACCESS" TO shareit WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES" TO shareit WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO shareit WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO shareit WITH ADMIN OPTION;
GRANT "STBROLE" TO shareit WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO shareit WITH ADMIN OPTION;
GRANT "LOGSTDBY_ADMINISTRATOR" TO shareit WITH ADMIN OPTION;
GRANT "AUTHENTICATEDUSER" TO shareit WITH ADMIN OPTION;
GRANT "OEM_ADVISOR" TO shareit WITH ADMIN OPTION;
GRANT "HS_ADMIN_ROLE" TO shareit WITH ADMIN OPTION;
GRANT "XDBADMIN" TO shareit WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO shareit WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO shareit WITH ADMIN OPTION;
GRANT DROP ANY CONTEXT TO shareit WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE TO shareit WITH ADMIN OPTION;
GRANT DROP ANY TRIGGER TO shareit WITH ADMIN OPTION;
GRANT MANAGE ANY FILE GROUP TO shareit WITH ADMIN OPTION;
GRANT ALTER PUBLIC DATABASE LINK TO shareit WITH ADMIN OPTION;
GRANT MANAGE FILE GROUP TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY INDEX TO shareit WITH ADMIN OPTION;
GRANT DROP ANY SEQUENCE TO shareit WITH ADMIN OPTION;
GRANT ALTER PROFILE TO shareit WITH ADMIN OPTION;
GRANT UNDER ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT CREATE ASSEMBLY TO shareit WITH ADMIN OPTION;
GRANT DROP ANY LIBRARY TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY EDITION TO shareit WITH ADMIN OPTION;
GRANT CREATE ROLE TO shareit WITH ADMIN OPTION;
GRANT CREATE LIBRARY TO shareit WITH ADMIN OPTION;
GRANT DROP ROLLBACK SEGMENT TO shareit WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY PROCEDURE TO shareit WITH ADMIN OPTION;
GRANT ADMINISTER DATABASE TRIGGER TO shareit WITH ADMIN OPTION;
GRANT DROP ANY MEASURE FOLDER TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY PROCEDURE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY OUTLINE TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ANY INDEXTYPE TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY DIRECTORY TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY RULE SET TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY MINING MODEL TO shareit WITH ADMIN OPTION;
GRANT DEBUG CONNECT SESSION TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY MINING MODEL TO shareit WITH ADMIN OPTION;
GRANT ALTER SESSION TO shareit WITH ADMIN OPTION;
GRANT CREATE MATERIALIZED VIEW TO shareit WITH ADMIN OPTION;
GRANT MERGE ANY VIEW TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY INDEX TO shareit WITH ADMIN OPTION;
GRANT CREATE DIMENSION TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE SET TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY MATERIALIZED VIEW TO shareit WITH ADMIN OPTION;
GRANT AUDIT SYSTEM TO shareit WITH ADMIN OPTION;
GRANT CREATE OPERATOR TO shareit WITH ADMIN OPTION;
GRANT MANAGE ANY QUEUE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY SQL PROFILE TO shareit WITH ADMIN OPTION;
GRANT GRANT ANY OBJECT PRIVILEGE TO shareit WITH ADMIN OPTION;
GRANT CREATE INDEXTYPE TO shareit WITH ADMIN OPTION;
GRANT AUDIT ANY TO shareit WITH ADMIN OPTION;
GRANT DEBUG ANY PROCEDURE TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY MEASURE FOLDER TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO shareit WITH ADMIN OPTION;
GRANT CREATE MEASURE FOLDER TO shareit WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE BUILD PROCESS TO shareit WITH ADMIN OPTION;
GRANT CREATE VIEW TO shareit WITH ADMIN OPTION;
GRANT ALTER DATABASE LINK TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY ASSEMBLY TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY EVALUATION CONTEXT TO shareit WITH ADMIN OPTION;
GRANT SELECT ANY MINING MODEL TO shareit WITH ADMIN OPTION;
GRANT DELETE ANY CUBE DIMENSION TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT CREATE SESSION TO shareit WITH ADMIN OPTION;
GRANT CREATE RULE TO shareit WITH ADMIN OPTION;
GRANT BECOME USER TO shareit WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT INSERT ANY MEASURE FOLDER TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY SQL PROFILE TO shareit WITH ADMIN OPTION;
GRANT FORCE ANY TRANSACTION TO shareit WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY SEQUENCE TO shareit WITH ADMIN OPTION;
GRANT SELECT ANY CUBE DIMENSION TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY EDITION TO shareit WITH ADMIN OPTION;
GRANT CREATE EXTERNAL JOB TO shareit WITH ADMIN OPTION;
GRANT DROP ANY MATERIALIZED VIEW TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY CUBE BUILD PROCESS TO shareit WITH ADMIN OPTION;
GRANT FLASHBACK ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT DROP ANY RULE SET TO shareit WITH ADMIN OPTION;
GRANT BACKUP ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY CUBE TO shareit WITH ADMIN OPTION;
GRANT CREATE TABLE TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ANY LIBRARY TO shareit WITH ADMIN OPTION;
GRANT DROP ANY OUTLINE TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ASSEMBLY TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY DIMENSION TO shareit WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY CLUSTER TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ANY CLASS TO shareit WITH ADMIN OPTION;
GRANT DROP ANY DIMENSION TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY RULE SET TO shareit WITH ADMIN OPTION;
GRANT SELECT ANY SEQUENCE TO shareit WITH ADMIN OPTION;
GRANT UNDER ANY TYPE TO shareit WITH ADMIN OPTION;
GRANT MANAGE TABLESPACE TO shareit WITH ADMIN OPTION;
GRANT DROP ANY OPERATOR TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY OPERATOR TO shareit WITH ADMIN OPTION;
GRANT EXEMPT IDENTITY POLICY TO shareit WITH ADMIN OPTION;
GRANT CREATE TYPE TO shareit WITH ADMIN OPTION;
GRANT CREATE TABLESPACE TO shareit WITH ADMIN OPTION;
GRANT SELECT ANY TRANSACTION TO shareit WITH ADMIN OPTION;
GRANT DELETE ANY MEASURE FOLDER TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY CUBE TO shareit WITH ADMIN OPTION;
GRANT LOCK ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT CREATE EVALUATION CONTEXT TO shareit WITH ADMIN OPTION;
GRANT DROP ANY TYPE TO shareit WITH ADMIN OPTION;
GRANT ADVISOR TO shareit WITH ADMIN OPTION;
GRANT CREATE PUBLIC DATABASE LINK TO shareit WITH ADMIN OPTION;
GRANT ANALYZE ANY TO shareit WITH ADMIN OPTION;
GRANT DROP ANY RULE TO shareit WITH ADMIN OPTION;
GRANT INSERT ANY CUBE DIMENSION TO shareit WITH ADMIN OPTION;
GRANT CREATE ROLLBACK SEGMENT TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY JOB TO shareit WITH ADMIN OPTION;
GRANT ALTER USER TO shareit WITH ADMIN OPTION;
GRANT QUERY REWRITE TO shareit WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO shareit WITH ADMIN OPTION;
GRANT CREATE PUBLIC SYNONYM TO shareit WITH ADMIN OPTION;
GRANT GLOBAL QUERY REWRITE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY CUBE DIMENSION TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY CUBE DIMENSION TO shareit WITH ADMIN OPTION;
GRANT DROP ANY CLUSTER TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY RULE TO shareit WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE DIMENSION TO shareit WITH ADMIN OPTION;
GRANT SYSDBA TO shareit WITH ADMIN OPTION;
GRANT ADMINISTER RESOURCE MANAGER TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO shareit WITH ADMIN OPTION;
GRANT DROP ANY SYNONYM TO shareit WITH ADMIN OPTION;
GRANT DROP ANY MINING MODEL TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO shareit WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ANY PROGRAM TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ANY TYPE TO shareit WITH ADMIN OPTION;
GRANT ON COMMIT REFRESH TO shareit WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO shareit WITH ADMIN OPTION;
GRANT COMMENT ANY MINING MODEL TO shareit WITH ADMIN OPTION;
GRANT ADMINISTER SQL TUNING SET TO shareit WITH ADMIN OPTION;
GRANT SYSOPER TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY INDEXTYPE TO shareit WITH ADMIN OPTION;
GRANT DROP ANY INDEX TO shareit WITH ADMIN OPTION;
GRANT RESTRICTED SESSION TO shareit WITH ADMIN OPTION;
GRANT DEQUEUE ANY QUEUE TO shareit WITH ADMIN OPTION;
GRANT ANALYZE ANY DICTIONARY TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY INDEXTYPE TO shareit WITH ADMIN OPTION;
GRANT ADMINISTER ANY SQL TUNING SET TO shareit WITH ADMIN OPTION;
GRANT CREATE USER TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ANY OPERATOR TO shareit WITH ADMIN OPTION;
GRANT CREATE CUBE BUILD PROCESS TO shareit WITH ADMIN OPTION;
GRANT CREATE PROFILE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO shareit WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY LIBRARY TO shareit WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY CLUSTER TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE TO shareit WITH ADMIN OPTION;
GRANT ALTER TABLESPACE TO shareit WITH ADMIN OPTION;
GRANT UNDER ANY VIEW TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ANY ASSEMBLY TO shareit WITH ADMIN OPTION;
GRANT GRANT ANY PRIVILEGE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO shareit WITH ADMIN OPTION;
GRANT EXPORT FULL DATABASE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY EVALUATION CONTEXT TO shareit WITH ADMIN OPTION;
GRANT FLASHBACK ARCHIVE ADMINISTER TO shareit WITH ADMIN OPTION;
GRANT IMPORT FULL DATABASE TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY OUTLINE TO shareit WITH ADMIN OPTION;
GRANT COMMENT ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT CREATE DATABASE LINK TO shareit WITH ADMIN OPTION;
GRANT DROP PUBLIC SYNONYM TO shareit WITH ADMIN OPTION;
GRANT DROP USER TO shareit WITH ADMIN OPTION;
GRANT CHANGE NOTIFICATION TO shareit WITH ADMIN OPTION;
GRANT CREATE MINING MODEL TO shareit WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT DROP PROFILE TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY MATERIALIZED VIEW TO shareit WITH ADMIN OPTION;
GRANT CREATE RULE SET TO shareit WITH ADMIN OPTION;
GRANT EXEMPT ACCESS POLICY TO shareit WITH ADMIN OPTION;
GRANT MANAGE SCHEDULER TO shareit WITH ADMIN OPTION;
GRANT READ ANY FILE GROUP TO shareit WITH ADMIN OPTION;
GRANT FORCE TRANSACTION TO shareit WITH ADMIN OPTION;
GRANT DROP ANY CUBE BUILD PROCESS TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY TYPE TO shareit WITH ADMIN OPTION;
GRANT DROP ANY PROCEDURE TO shareit WITH ADMIN OPTION;
GRANT DROP PUBLIC DATABASE LINK TO shareit WITH ADMIN OPTION;
GRANT DROP ANY INDEXTYPE TO shareit WITH ADMIN OPTION;
GRANT DROP ANY SQL PROFILE TO shareit WITH ADMIN OPTION;
GRANT ALTER SYSTEM TO shareit WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO shareit WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY DIMENSION TO shareit WITH ADMIN OPTION;
GRANT DROP ANY CUBE DIMENSION TO shareit WITH ADMIN OPTION;
GRANT DROP ANY CUBE TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO shareit WITH ADMIN OPTION;
GRANT DROP ANY ASSEMBLY TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO shareit WITH ADMIN OPTION;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO shareit WITH ADMIN OPTION;
GRANT DROP ANY DIRECTORY TO shareit WITH ADMIN OPTION;
GRANT ENQUEUE ANY QUEUE TO shareit WITH ADMIN OPTION;
GRANT DROP ANY EVALUATION CONTEXT TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY ASSEMBLY TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY TYPE TO shareit WITH ADMIN OPTION;
GRANT CREATE CLUSTER TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY CONTEXT TO shareit WITH ADMIN OPTION;
GRANT EXECUTE ANY EVALUATION CONTEXT TO shareit WITH ADMIN OPTION;
GRANT RESUMABLE TO shareit WITH ADMIN OPTION;
GRANT CREATE ANY LIBRARY TO shareit WITH ADMIN OPTION;
GRANT DROP ANY EDITION TO shareit WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO shareit WITH ADMIN OPTION;
GRANT ALTER DATABASE TO shareit WITH ADMIN OPTION;
GRANT SELECT ANY CUBE TO shareit WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY RULE TO shareit WITH ADMIN OPTION;
GRANT CREATE CUBE DIMENSION TO shareit WITH ADMIN OPTION;
GRANT ALTER ANY OPERATOR TO shareit WITH ADMIN OPTION;
GRANT CREATE CUBE TO shareit WITH ADMIN OPTION;
GRANT ALTER RESOURCE COST TO shareit WITH ADMIN OPTION;
GRANT DROP TABLESPACE TO shareit WITH ADMIN OPTION;
GRANT ALTER ROLLBACK SEGMENT TO shareit WITH ADMIN OPTION;

 
--------------------------------------------------------
DROP TABLE "SHAREIT"."T_ACTIVITY";
DROP TABLE "SHAREIT"."T_ADDRESS";
DROP TABLE "SHAREIT"."T_CATEGORY";
DROP TABLE "SHAREIT"."T_CITY";
DROP TABLE "SHAREIT"."T_COUNTRY";
DROP TABLE "SHAREIT"."T_GENDER";
DROP TABLE "SHAREIT"."T_ITEM";
DROP TABLE "SHAREIT"."T_STATE";
DROP TABLE "SHAREIT"."T_USER";
DROP SEQUENCE "SHAREIT"."TABLE1_SEQ";
DROP SEQUENCE "SHAREIT"."T_ACTIVITY_SEQ";
DROP SEQUENCE "SHAREIT"."T_ADDRESS_SEQ";
DROP SEQUENCE "SHAREIT"."T_CATEGORY_SEQ";
DROP SEQUENCE "SHAREIT"."T_CITY_SEQ";
DROP SEQUENCE "SHAREIT"."T_COUNTRY_SEQ";
DROP SEQUENCE "SHAREIT"."T_GENDER_SEQ";
DROP SEQUENCE "SHAREIT"."T_ITEM_SEQ";
DROP SEQUENCE "SHAREIT"."T_STATE_SEQ";
DROP SEQUENCE "SHAREIT"."T_USER_SEQ";
--------------------------------------------------------
--  DDL for Table T_ACTIVITY
--------------------------------------------------------

  CREATE TABLE "SHAREIT"."T_ACTIVITY" 
   (	"ID" NUMBER, 
	"ITEM" NUMBER, 
	"FROM_USER" NUMBER, 
	"TO_USER" NUMBER, 
	"MEETING_POINT" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"TIME_FROM" TIMESTAMP (6), 
	"TIME_TO" TIMESTAMP (6), 
	"ACTIVITY_DELETED" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_ADDRESS
--------------------------------------------------------

  CREATE TABLE "SHAREIT"."T_ADDRESS" 
   (	"ID" NUMBER, 
	"R_USER" NUMBER, 
	"COUNTRY" NUMBER, 
	"CITY" NUMBER, 
	"STATE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_CATEGORY
--------------------------------------------------------

  CREATE TABLE "SHAREIT"."T_CATEGORY" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"MAX_POINTS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_CITY
--------------------------------------------------------

  CREATE TABLE "SHAREIT"."T_CITY" 
   (	"ID" NUMBER, 
	"CITY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_COUNTRY
--------------------------------------------------------

  CREATE TABLE "SHAREIT"."T_COUNTRY" 
   (	"ID" NUMBER, 
	"COUNTRY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_GENDER
--------------------------------------------------------

  CREATE TABLE "SHAREIT"."T_GENDER" 
   (	"ID" NUMBER, 
	"GENDER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_ITEM
--------------------------------------------------------

  CREATE TABLE "SHAREIT"."T_ITEM" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"CATEGORY" NUMBER, 
	"IS_AVAILABLE" NUMBER(1,0), 
	"PUBLISH_DATE" TIMESTAMP (6), 
	"POINTS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_STATE
--------------------------------------------------------

  CREATE TABLE "SHAREIT"."T_STATE" 
   (	"ID" NUMBER, 
	"STATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_USER
--------------------------------------------------------

  CREATE TABLE "SHAREIT"."T_USER" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"IMAGE_URL" VARCHAR2(200 BYTE), 
	"POINTS" NUMBER, 
	"GENDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence TABLE1_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHAREIT"."TABLE1_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence T_ACTIVITY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHAREIT"."T_ACTIVITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence T_ADDRESS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHAREIT"."T_ADDRESS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence T_CATEGORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHAREIT"."T_CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence T_CITY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHAREIT"."T_CITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence T_COUNTRY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHAREIT"."T_COUNTRY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence T_GENDER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHAREIT"."T_GENDER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence T_ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHAREIT"."T_ITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence T_STATE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHAREIT"."T_STATE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence T_USER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHAREIT"."T_USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Index T_CATEGORY_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_CATEGORY_UK1" ON "SHAREIT"."T_CATEGORY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_CATEGORY_PK" ON "SHAREIT"."T_CATEGORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_ADDRESS_PK" ON "SHAREIT"."T_ADDRESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."TABLE1_UK1" ON "SHAREIT"."T_ITEM" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."TABLE1_PK" ON "SHAREIT"."T_ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_COUNTRY_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_COUNTRY_UK1" ON "SHAREIT"."T_COUNTRY" ("COUNTRY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_CITY_PK" ON "SHAREIT"."T_CITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_STATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_STATE_PK" ON "SHAREIT"."T_STATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_COUNTRY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_COUNTRY_PK" ON "SHAREIT"."T_COUNTRY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_GENDER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_GENDER_UK1" ON "SHAREIT"."T_GENDER" ("GENDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_ADDRESS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_ADDRESS_UK1" ON "SHAREIT"."T_ADDRESS" ("COUNTRY", "CITY", "STATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_CITY_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_CITY_UK1" ON "SHAREIT"."T_CITY" ("CITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_ACTIVITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_ACTIVITY_PK" ON "SHAREIT"."T_ACTIVITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_USER_PK" ON "SHAREIT"."T_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_GENDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_GENDER_PK" ON "SHAREIT"."T_GENDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_USER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_USER_UK1" ON "SHAREIT"."T_USER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_STATE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_STATE_UK1" ON "SHAREIT"."T_STATE" ("STATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger T_ACTIVITY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHAREIT"."T_ACTIVITY_TRG" 
BEFORE INSERT ON "SHAREIT"."T_ACTIVITY"
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT T_ACTIVITY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SHAREIT"."T_ACTIVITY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ADDRESS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHAREIT"."T_ADDRESS_TRG" 
BEFORE INSERT ON "SHAREIT"."T_ADDRESS"
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT T_ADDRESS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SHAREIT"."T_ADDRESS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_CATEGORY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHAREIT"."T_CATEGORY_TRG" 
BEFORE INSERT ON "SHAREIT"."T_CATEGORY"
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT T_CATEGORY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SHAREIT"."T_CATEGORY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_CITY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHAREIT"."T_CITY_TRG" 
BEFORE INSERT ON "SHAREIT"."T_CITY"
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT T_CITY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SHAREIT"."T_CITY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_COUNTRY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHAREIT"."T_COUNTRY_TRG" 
BEFORE INSERT ON "SHAREIT"."T_COUNTRY"
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT T_COUNTRY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SHAREIT"."T_COUNTRY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_GENDER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHAREIT"."T_GENDER_TRG" 
BEFORE INSERT ON "SHAREIT"."T_GENDER"
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT T_GENDER_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SHAREIT"."T_GENDER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ITEM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHAREIT"."T_ITEM_TRG" 
BEFORE INSERT ON "SHAREIT"."T_ITEM"
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
 IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT T_ITEM_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SHAREIT"."T_ITEM_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_STATE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHAREIT"."T_STATE_TRG" 
BEFORE INSERT ON "SHAREIT"."T_STATE"
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT T_STATE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SHAREIT"."T_STATE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_USER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHAREIT"."T_USER_TRG" 
BEFORE INSERT ON "SHAREIT"."T_USER"
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT T_USER_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SHAREIT"."T_USER_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table T_USER
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_USER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_USER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_USER" MODIFY ("POINTS" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_USER" ADD CONSTRAINT "T_USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_USER" ADD CONSTRAINT "T_USER_UK1" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_USER" MODIFY ("GENDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_COUNTRY
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_COUNTRY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_COUNTRY" ADD CONSTRAINT "T_COUNTRY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_COUNTRY" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_COUNTRY" ADD CONSTRAINT "T_COUNTRY_UK1" UNIQUE ("COUNTRY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_STATE
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_STATE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_STATE" ADD CONSTRAINT "T_STATE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_STATE" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_STATE" ADD CONSTRAINT "T_STATE_UK1" UNIQUE ("STATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_ADDRESS
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_ADDRESS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ADDRESS" MODIFY ("R_USER" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ADDRESS" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ADDRESS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ADDRESS" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ADDRESS" ADD CONSTRAINT "T_ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_ADDRESS" ADD CONSTRAINT "T_ADDRESS_UK1" UNIQUE ("COUNTRY", "CITY", "STATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_CITY
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_CITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_CITY" ADD CONSTRAINT "T_CITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_CITY" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_CITY" ADD CONSTRAINT "T_CITY_UK1" UNIQUE ("CITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_ITEM
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_ITEM" MODIFY ("POINTS" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ITEM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ITEM" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ITEM" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ITEM" MODIFY ("IS_AVAILABLE" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ITEM" MODIFY ("PUBLISH_DATE" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ITEM" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_ITEM" ADD CONSTRAINT "TABLE1_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_CATEGORY
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_CATEGORY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_CATEGORY" ADD CONSTRAINT "T_CATEGORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_CATEGORY" ADD CONSTRAINT "T_CATEGORY_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_CATEGORY" MODIFY ("MAX_POINTS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GENDER
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_GENDER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_GENDER" ADD CONSTRAINT "T_GENDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_GENDER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_GENDER" ADD CONSTRAINT "T_GENDER_UK1" UNIQUE ("GENDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_ACTIVITY
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("ITEM" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("FROM_USER" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("TO_USER" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("MEETING_POINT" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("TIME_FROM" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("TIME_TO" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("ACTIVITY_DELETED" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" ADD CONSTRAINT "T_ACTIVITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_ACTIVITY
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_ACTIVITY" ADD CONSTRAINT "T_ACTIVITY_FK1" FOREIGN KEY ("ITEM")
	  REFERENCES "SHAREIT"."T_ITEM" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SHAREIT"."T_ACTIVITY" ADD CONSTRAINT "T_ACTIVITY_FK2" FOREIGN KEY ("FROM_USER")
	  REFERENCES "SHAREIT"."T_USER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SHAREIT"."T_ACTIVITY" ADD CONSTRAINT "T_ACTIVITY_FK3" FOREIGN KEY ("TO_USER")
	  REFERENCES "SHAREIT"."T_USER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_ADDRESS
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_ADDRESS" ADD CONSTRAINT "T_ADDRESS_FK1" FOREIGN KEY ("R_USER")
	  REFERENCES "SHAREIT"."T_USER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SHAREIT"."T_ADDRESS" ADD CONSTRAINT "T_ADDRESS_FK2" FOREIGN KEY ("COUNTRY")
	  REFERENCES "SHAREIT"."T_COUNTRY" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SHAREIT"."T_ADDRESS" ADD CONSTRAINT "T_ADDRESS_FK3" FOREIGN KEY ("CITY")
	  REFERENCES "SHAREIT"."T_CITY" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SHAREIT"."T_ADDRESS" ADD CONSTRAINT "T_ADDRESS_FK4" FOREIGN KEY ("STATE")
	  REFERENCES "SHAREIT"."T_STATE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_ITEM
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_ITEM" ADD CONSTRAINT "TABLE1_FK1" FOREIGN KEY ("CATEGORY")
	  REFERENCES "SHAREIT"."T_CATEGORY" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_USER
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_USER" ADD CONSTRAINT "T_USER_FK1" FOREIGN KEY ("GENDER")
	  REFERENCES "SHAREIT"."T_GENDER" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "SHAREIT"."T_ITEM" 
DROP CONSTRAINT TABLE1_UK1;
