--------------------------------------------------------
--  File created - Monday-May-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_ACTIVITY
--------------------------------------------------------

drop table "SHAREIT"."T_ACTIVITY" cascade constraints;

  CREATE TABLE "SHAREIT"."T_ACTIVITY" 
   (	"ID" NUMBER, 
	"ITEM" NUMBER, 
	"FROM_USER" NUMBER, 
	"TO_USER" NUMBER, 
	"MEETING_POINT" VARCHAR2(200 BYTE), 
	"STATUS" NUMBER, 
	"TIME_FROM" TIMESTAMP (6), 
	"TIME_TO" TIMESTAMP (6), 
	"ACTIVITY_DELETED" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_STATUS
--------------------------------------------------------

  CREATE TABLE "SHAREIT"."T_STATUS" 
   (	"ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Sequence T_STATUS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHAREIT"."T_STATUS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into SHAREIT.T_ACTIVITY
SET DEFINE OFF;
Insert into SHAREIT.T_ACTIVITY (ID,ITEM,FROM_USER,TO_USER,MEETING_POINT,STATUS,TIME_FROM,TIME_TO,ACTIVITY_DELETED) values (22,7,1,21,'fds',2,to_timestamp('29-MAY-17 07.53.03.188000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('31-MAY-17 07.53.08.563000000 AM','DD-MON-RR HH.MI.SSXFF AM'),0);
REM INSERTING into SHAREIT.T_STATUS
SET DEFINE OFF;
Insert into SHAREIT.T_STATUS (ID,STATUS) values (1,'Pending');
Insert into SHAREIT.T_STATUS (ID,STATUS) values (2,'Accepted');
Insert into SHAREIT.T_STATUS (ID,STATUS) values (3,'Declined');
--------------------------------------------------------
--  DDL for Index T_ACTIVITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_ACTIVITY_PK" ON "SHAREIT"."T_ACTIVITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHAREIT"."T_STATUS_PK" ON "SHAREIT"."T_STATUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Trigger T_STATUS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHAREIT"."T_STATUS_TRG" 
BEFORE INSERT ON T_STATUS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT T_STATUS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SHAREIT"."T_STATUS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table T_ACTIVITY
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_ACTIVITY" ADD CONSTRAINT "T_ACTIVITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("ACTIVITY_DELETED" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("TIME_TO" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("TIME_FROM" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("MEETING_POINT" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("TO_USER" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("FROM_USER" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("ITEM" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_ACTIVITY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_STATUS
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_STATUS" ADD CONSTRAINT "T_STATUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHAREIT"."T_STATUS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SHAREIT"."T_STATUS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table T_ACTIVITY
--------------------------------------------------------

  ALTER TABLE "SHAREIT"."T_ACTIVITY" ADD CONSTRAINT "T_ACTIVITY_FK1" FOREIGN KEY ("ITEM")
	  REFERENCES "SHAREIT"."T_ITEM" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SHAREIT"."T_ACTIVITY" ADD CONSTRAINT "T_ACTIVITY_FK2" FOREIGN KEY ("FROM_USER")
	  REFERENCES "SHAREIT"."T_USER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SHAREIT"."T_ACTIVITY" ADD CONSTRAINT "T_ACTIVITY_FK3" FOREIGN KEY ("TO_USER")
	  REFERENCES "SHAREIT"."T_USER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SHAREIT"."T_ACTIVITY" ADD CONSTRAINT "T_ACTIVITY_FK4" FOREIGN KEY ("STATUS")
	  REFERENCES "SHAREIT"."T_STATUS" ("ID") ON DELETE CASCADE ENABLE;
      
      
